# Generated by Django 3.2.12 on 2024-02-26 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('ID', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('TAC', models.IntegerField()),
            ],
        ),
    ]
