# Generated by Django 3.2.12 on 2024-02-26 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0002_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='ID',
            new_name='idCard',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='TAC',
            new_name='number',
        ),
    ]
