# Generated by Django 3.2.12 on 2024-02-26 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0003_auto_20240226_0739'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('location', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
            ],
        ),
    ]
