# Generated by Django 3.2.12 on 2024-02-27 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0004_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='category',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='school',
            name='location',
            field=models.CharField(max_length=25),
        ),
    ]
