# Generated by Django 3.2.12 on 2024-02-27 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0005_auto_20240227_0459'),
    ]

    operations = [
        migrations.DeleteModel(
            name='School',
        ),
    ]
